local Stack = require("nurl.utils.stack")

describe("utils.stack", function()
    describe("new", function()
        it("creates stack with specified max_items", function()
            local stack = Stack:new(10)
            assert.are.equal(10, stack.max_items)
            assert.are.same({}, stack.items)
        end)
    end)

    describe("push", function()
        it("adds item to stack", function()
            local stack = Stack:new(10)
            stack:push("a")
            assert.are.same({ "a" }, stack.items)
        end)

        it("adds multiple items", function()
            local stack = Stack:new(10)
            stack:push("a")
            stack:push("b")
            stack:push("c")
            assert.are.same({ "a", "b", "c" }, stack.items)
        end)

        it("does not push duplicate at tip", function()
            local stack = Stack:new(10)
            stack:push("a")
            stack:push("a")
            assert.are.same({ "a" }, stack.items)
        end)

        it("allows duplicate if not at tip", function()
            local stack = Stack:new(10)
            stack:push("a")
            stack:push("b")
            stack:push("a")
            assert.are.same({ "a", "b", "a" }, stack.items)
        end)

        it("trims oldest items when exceeding max", function()
            local stack = Stack:new(3)
            stack:push(1)
            stack:push(2)
            stack:push(3)
            stack:push(4)
            assert.are.same({ 2, 3, 4 }, stack.items)
        end)

        it("uses deep_equal for duplicate check", function()
            local stack = Stack:new(10)
            stack:push({ a = 1 })
            stack:push({ a = 1 })
            assert.are.equal(1, #stack.items)
        end)
    end)

    describe("get", function()
        local stack

        before_each(function()
            stack = Stack:new(10)
            stack:push("a")
            stack:push("b")
            stack:push("c")
        end)

        it("gets item by positive index", function()
            assert.are.equal("a", stack:get(1))
            assert.are.equal("b", stack:get(2))
            assert.are.equal("c", stack:get(3))
        end)

        it("gets item by negative index", function()
            assert.are.equal("c", stack:get(-1))
            assert.are.equal("b", stack:get(-2))
            assert.are.equal("a", stack:get(-3))
        end)

        it("returns nil for out of bounds positive index", function()
            assert.is_nil(stack:get(4))
        end)

        it("returns nil for out of bounds negative index", function()
            assert.is_nil(stack:get(-4))
        end)

        it("returns nil for index 0", function()
            assert.is_nil(stack:get(0))
        end)
    end)
end)
