name: Generate docs
on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/docs.yml
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p doc
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: ${{ github.event.repository.name }}
          version: "Neovim >= 0.10.0"
          shiftheadinglevelby: -1 # remove README.md first nurl.nvim header from tags
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto-generate vimdoc"
          file_pattern: doc/*
